# Generated by Django 4.2.4 on 2023-09-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen type'), ('client', 'Client type')], max_length=7)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Kitchen type'), ('client', 'Client type')], max_length=7)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'New status'), ('rendered', 'Rendered status'), ('printed', 'Printed status')], max_length=8)),
                ('pdf_file', models.FileField(upload_to='media/pdf')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printer')),
            ],
        ),
    ]
