# Generated by Django 4.2.4 on 2023-09-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(upload_to='./media/pdf'),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], max_length=8),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=7),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=7),
        ),
    ]
