# Generated by Django 4.2.4 on 2023-09-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_check_pdf_file_alter_check_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='./media/pdf'),
        ),
    ]
